In [3]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [6]:
a.shape

(2, 7)

In [8]:
a.itemsize

8

# Getting a Specific Element

In [9]:
# Getting a specific element [r, c]
# Where r is the index of the element row and c is the column index of the element

In [12]:
# accessing 6 in the array a

a1 = a[0, 5]

In [13]:
print(a1)

6


In [11]:
a[0, -2]

np.int64(6)

# Getting a specific row and column

In [16]:
# Getting the first row

a1_row = a[0, : ]
a1_row

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Getting a specific column

a1_column = a[:, 3]
a1_column

array([ 4, 11])

In [23]:
 # [startindex: endindex: stepsize]

a1_step = a[0, 2: 7: 2]
a1_step

array([3, 5, 7])