In [1]:
import numpy as np

# Common array Constructors

In [7]:
# 4x6 array filled with 0

arr_zeros = np.zeros((4, 6))

In [8]:
arr_zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
# Array filled with ones (1)

arr_ones = np.ones((3, 5))

In [6]:
arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Identity matrix

arr_identity = np.eye(4)

In [14]:
arr_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
# Filling a given array with a specific number

arr_fill = np.full((2, 2,), 6)