In [2]:
import numpy as np

# The Basics

In [3]:
# Initializing arrays

a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
# Two-dimensional array

b = np.array([[1, 2, 3, 4], [3, 7, 8, 9]])

In [6]:
print(b)

[[1 2 3 4]
 [3 7 8 9]]


In [7]:
# Getting dimensions

a.ndim # ndim stands for number of dimensions

1

In [8]:
b.ndim

2

In [9]:
# Getting shape

a.shape

(3,)

In [10]:
b.shape

(2, 4)

In [11]:
# Getting type

a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('int64')

In [13]:
# Getting size and totalsize

a.itemsize

8

In [14]:
b.itemsize

8

In [15]:
# Getting the total size

a.size * a.itemsize

24

In [16]:
b.size * b.itemsize

64

In [17]:
# nytes full as number of bytes can be used to calculate the total size

a.nbytes

24