In [1]:
import numpy as np

In [12]:
a = np.array([1, 2, 3, 4, 5])

In [13]:
b = np.array([6, 7, 8, 9, 10])

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
b

array([ 6,  7,  8,  9, 10])

In [18]:
arr1 = a[1: 5: 2]

In [19]:
arr1

array([2, 4])

In [20]:
sum = a + b
sum

array([ 7,  9, 11, 13, 15])

In [21]:
product = a * b
product

array([ 6, 14, 24, 36, 50])

In [22]:
square = a ** b
square

array([      1,     128,    6561,  262144, 9765625])

In [23]:
square_root = np.sqrt(square)
square_root

array([1.00000000e+00, 1.13137085e+01, 8.10000000e+01, 5.12000000e+02,
       3.12500000e+03])

In [24]:
np.sqrt(square[1])

np.float64(11.313708498984761)